# Generated by Django 3.0.2 on 2020-01-29 17:02

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.Base')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('image', stdimage.models.StdImageField(upload_to='postimage', verbose_name='Imagem')),
                ('cargo', models.CharField(choices=[('Presidente', 'Presidente'), ('Vice Presidente', 'Vice Presidente'), ('Secretário Geral', 'Secretário Geral'), ('Tesoureiro', 'Tesoureiro'), ('Diretor de comunicação', 'Diretor de comunicação'), ('Membro', 'Membro')], max_length=25, verbose_name='Cargo')),
            ],
            bases=('homepage.base',),
        ),
    ]
