# Generated by Django 3.0.2 on 2020-01-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_membros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membros',
            options={'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
    ]
