# Generated by Django 3.0.2 on 2020-01-29 20:51

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_membros_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.Base')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('image', stdimage.models.StdImageField(upload_to='postimage', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Laboratório',
                'verbose_name_plural': 'Laboratórios',
            },
            bases=('homepage.base',),
        ),
    ]
